# see http://www.martyndavis.com/?p=335 for required hack on Ubuntu Precise
# see http://mjo.tc/atelier/2009/02/arduino-cli.html

ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = pro328
ARDUINO_PORT = /dev/envmon /dev/ttyUSB*
ARDUINO_LIBS = EEPROM Wire UDEV
include /usr/share/arduino/Arduino.mk
